spring:
  config:
    activate:
      on-profile: '!api-docs'
springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /api-docs
---
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include:
          - configprops
          - env
          - health
          - info
          - logfile
          - loggers
          - threaddump
          - caches
          - liquibase
  endpoint:
    health:
      show-details: when_authorized
      roles: 'ROLE_ADMIN'
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState
        readiness:
          include: readinessState,db
  info:
    git:
      mode: full
    env:
      enabled: true
  health:
    mail:
      enabled: false

spring:
  application:
    name: DemoApplication
  profiles:
    active: #spring.profiles.active#
    group:
      dev:
        - dev
        - api-docs
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:postgresql://localhost:5432/demo
    type: com.zaxxer.hikari.HikariDataSource
    username: admin
    # password hardcoded for demo purposes only.
    password: admin
  hikari:
    poolName: Hikari
    auto-commit: false
  liquibase:
    contexts: dev
    enabled: true
    default-schema: public
    drop-first: false
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.timezone.default_storage: NORMALIZE
      hibernate.type.preferred_instant_jdbc_type: TIMESTAMP
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  messages:
    basename: i18n/messages
    cache-duration: PT1S
  main:
    allow-bean-definition-overriding: true
  mvc:
    problemdetails:
      enabled: true
  task:
    execution:
      thread-name-prefix: goal.demo-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
    scheduling:
      thread-name-prefix: goal.demo-scheduling-
      pool:
        size: 2
  output:
    ansi:
      console-available: true

server:
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true

logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.goal.demo: DEBUG
