# This configuration is intended for development purpose
name: demo
services:
  postgresql:
    image: postgres:latest
    container_name: postgres-db
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER}']
      interval: 60s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
